@startuml
scale 650 width
state 机票订单状态 {
  [*] --> 下单中: 创建订单中
  state 下单中
  下单中 --> 订单创建失败: 下单失败
  订单创建失败->[*]
  下单中 --> 待审批: 需要审批
  待审批 --> 出票中: 供应商下单支付失败或收银支付失败
  待审批 --> 待支付: 供应商下单成功
  下单中 --> 待支付: 下单成功
  待支付 --> 已取消: 客户主动取消
  待支付 --> 已关闭: 超时未支付
  已取消->[*]
  已关闭->[*]
  待支付 --> 出票中: 支付成功
  出票成功->[*]
  出票中 --> 出票成功
  出票成功 --> 机票退票
  出票成功 --> 机票改签
  出票中 -> 出票失败
  出票失败->[*]

state 机票退票 {
  退票中-->退票成功
  退票中:订单状态为有退改签
  退票中:票状态为退票中
  退票成功:原单订单状态为有退改签\n票状态为退票成功\n新单状态都为退票成功
  退票中-->退票失败
  退票失败:不生成新单\n订单状态为有退改签\n票状态为退票失败
  退票成功-->[*]
  退票失败-->[*]
}
state 机票改签 {
  改签中-->改签成功
  改签中:订单状态为有退改签
  改签中:票状态为改签中
  改签成功:原单订单状态为有退改签\n票状态为改签成功\n新单状态都为改签成功
  改签中-->改签失败
  改签失败:不生成新单\n订单状态为有退改签\n票状态为改签失败
  改签成功-->[*]
  改签失败-->[*]
}
}

@enduml